### PR TITLE
Login signup fix

### LINKED ISSUE #41: Login & Signup page layout and bug

### PR DESCRIPTION
**Pull request by oyunerdene-m**
Fixes #41

### CODE REVIEW

File: front/src/lib/getLastTransactions.js [hunk 1]
```diff
@@ -16,5 +16,18 @@ export default function getLastTransactions(transactions) {
 		return bDate - aDate;
 	});
 
-	return [transactions[0], transactions[1], transactions[2]];
+	const res = [];
+	let count = 0;
+	for (let el of transactions) {
```
Comment (delgermurun) [inline front/src/lib/getLastTransactions.js:21]: there must be built in array method that takes first N elements of array.
Please use that.

**Review by delgermurun — CHANGES_REQUESTED** [review]

File: front/src/lib/getLastTransactions.js (hunk 1 above)
Comment (oyunerdene-m) [reply front/src/lib/getLastTransactions.js]: done

**Review by delgermurun — APPROVED** [review]
